name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Backend Unit Tests (Jest)
        run: npm --prefix back run test

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: my-image

#       - name: Deploy to DigitalOcean App Platform
#         uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrets.DO_API_TOKEN }}
#           command: |
#             doctl apps create --spec .do/app.yaml
#             doctl apps create-deployment my-app --image my-image:${{ github.sha }}
